description = "Static base image (Ubuntu Noble Numbat build image, distroless-like run image) with no buildpacks included. To use, specify buildpacks at build time."

[lifecycle]
  version = "0.19.6"

[stack]
  build-image = "docker.io/paketobuildpacks/build-noble-static:0.0.1"
  id = "io.buildpacks.stacks.noble.static"
  run-image = "index.docker.io/paketobuildpacks/run-noble-static:latest"
  run-image-mirrors = []
